### PR TITLE
fix(docs): Grammatical Error correction

### PR DESCRIPTION
**Pull request by im-coder-lg**
## Motivation

I observed that the docs have a lot of grammatical errors so I am aiming to fix it through this PR

## Changes

Almost every single file in the documentation(mostly the important ones)

## Related

Nothing related here as of now.

## Additional Comments

I could finish everything in a week since the docs have a lot of files, I need to go through them when I am free, and I have a genuine suggestion: Last time, you said that Docusaurus is buggy sometimes, so why not use CODEDOC? CODEDOC is another documentation source like Docusaurus and everything there is really minimal. You get a footer, where you can link your repository, add starring buttons, link a Gitter community(if you want) and create custom components from TypeScript. So, if you want to switch, you can ask me anytime. Documentation of CODEDOC is over on https://codedoc.cc and yeah, it doesn't work with Vercel but with GitHub Pages, and I have an idea for that :wink:

### CODE REVIEW

**Comment by im-coder-lg** [comment]
And, the docs will be hosted on GitHub Pages, and don't worry, I have a plan to push it there whenever the docs or the entire repo is updated. I will make a GitHub Action where it will deploy the webpage on push and exactly two and a half minutes later, it will be up. Favicons are supported, and you can add buttons, customize themes, and build the webpage immediately too.
Don't worry, I will help here, I will make the branch and allow edits by maintainers(you) so you can inspect the webpage whenever you want.

Extra note: CODEDOC has its own CLI and you can get the boilerplate theme from there, but you can actually use NPM to get dependencies.

**Comment by im-coder-lg** [comment]
Ah, everything is successful! More correction and I will release this for review.

**Comment by im-coder-lg** [comment]
Gitpod link: [https://gitpod.io/#https://github.com/im-coder-lg/xplorer/tree/im-coder-lg-corrections](https://gitpod.io/#https://github.com/im-coder-lg/xplorer/tree/im-coder-lg-corrections)

**Comment by kimlimjustin** [comment]
For the CODECOC, is it based on React? What I mean with buggy is that when I build it (production), the link is broken (you can see the electron link on the main page there) and I opened a PR there and they said it's probably because of React, so ......


Also, tbh, the Docusaurus website is more elegant tho...

**Comment by im-coder-lg** [comment]
CODEDOC is built around TSX and TS but you use Markdown for the documentation.

**Comment by im-coder-lg** [comment]
CODEDOC is built around TSX and TS but you use Markdown for the documentation.

**Comment by kimlimjustin** [comment]
The problem is if I use it as documentation, it surely has to be styled, which is an effort...

**Comment by im-coder-lg** [comment]
And I have been using it for a few months and noticed that unless the link is incorrect, it loads the link up. Examples are my [blog](https://coderlg.coding.blog), my project, Comboser's [docs](https://comboser.github.io/docs)

Yeah, the Comboser Docs is hosted on GitHub.

**Comment by im-coder-lg** [comment]
Sorry for that, I was using my phone and now switched to laptop(the phone 
didn't get synced), you don't need to switch styles, just get the hex code 
and put it in the themes file(typescript)

**Comment by im-coder-lg** [comment]
> The problem is if I use it as documentation, it surely has to be styled, which is an effort...

Maybe I can help in the styling. Since I learnt what files are supposed to be configured, I can set a specific color for the button and another for the themes, etc.

**Comment by kimlimjustin** [comment]
I don't think Ill change it into CODECOC since yeah the UX is quite annoying (at least for me), if you are saying about changing to next js, I might consider it, thanks tho

Also, Im not talking only the color, the sidebar is a bad choice tho

**Comment by im-coder-lg** [comment]
oh yeah @kimlimjustin I found some kind of error with Algoria, it does show search results but doesn't open the respective pages, is this internal or external?

**Comment by kimlimjustin** [comment]
Its problem with algolia (the docs is always being updated tho, maybe algolia hasn't crawl it(?))

**Comment by im-coder-lg** [comment]
Hey @kimlimjustin the PR is ready. You have a failing workflow in build and it is due to a token, so can you try fixing it soon?

**Review by kimlimjustin — APPROVED** [review]

**Comment by kimlimjustin** [comment]
> Hey @kimlimjustin the PR is ready. You have a failing workflow in build and it is due to a token, so can you try fixing it soon?

Fixed it via 469633c3cb51be8339127fd45bca8e7593a81cad

**Pull request merged**
