### PR TITLE
UI Enhancement

### PR DESCRIPTION
**Pull request by dkhd**
Hi @kimlimjustin 

Please take a look at this PR.

## Motivation

After forking the repository, I spotted several parts that are related to UIs that can be improved like font size, padding, margin, etc, so I make the changes. This PR is purely for aesthetic purpose. 

## Changes

There are several changes I've made, and some of them are:
- Reducing the font size
- Increasing the padding & margin on the sidebar
- Removing the border & background from Favorites & Drives at main panel (those were look like selected-state before the changes)
- Increasing context menu padding
- Adding context menu hover state
- Moving the "Settings" text to left side, as well as the back button

Please take a look at these screenshots below (I'm using Elementary OS 6) to see the changes:

Home; dark
 
Context menu; dark

Home; light

Context menu; light

## Related

_None_

## Additional Comments

During the development, I found these two issues (UI-related issues). I will submit these to the issue tab later, but I will put them here first:
- To make the selected-state active in the "Favorite" and "Drives" section in the main panel (not sidebar), it can only be clicked/activated from the edge of the border in hover state
- Context menu is clipped if opened at the edge of the window

### CODE REVIEW

**Review by kimlimjustin — APPROVED** [review]
The design looks good to me! TYSM!

**Comment by kimlimjustin** [comment]
Oops, it seems like you edited the `yarn.lock` file and the workflow failed. I'll take a look into it.

**Comment by kimlimjustin** [comment]
I'm really sorry but the `favorites` section and the `drives` section layout are also being affected when changing `Layout Mode`, could you please deliver a fix for that @dkhd? It's okay if you're not available tho :)

Salam

**Comment by dkhd** [comment]
Hi @kimlimjustin 

Sure I'll check it. But maybe tomorrow? Currently I'm not available.

What do you think?

**Comment by kimlimjustin** [comment]
> Hi @kimlimjustin
> 
> Sure I'll check it. But maybe tomorrow? Currently I'm not available.
> 
> What do you think?

It's okay (I need to do my homework too haha), thanks and sorry for disturbing you

**Comment by dkhd** [comment]
Haha. No worries, young man..

You did a great job 👍

**Comment by dkhd** [comment]
hi @kimlimjustin

Please kindly check your email :)

**Pull request merged**
