### PR TITLE
feat: Gitpod Support

### PR DESCRIPTION
**Pull request by im-coder-lg**
## Motivation

Info on #83 

## Changes

Added Gitpod Dockerfile+Config
<s>Added Server Shell script for automation.</s>

## Related

#83 #69 has more info than this

## Additional Comments

Must modify docs, CONTRIBUTING.md and README.md

### CODE REVIEW

**Comment by im-coder-lg** [comment]
@kimlimjustin here it is, there's not any kind of big commit activities at all in this.

**Comment by im-coder-lg** [comment]
Don't merge this until the documentation is updated with the latest info of this.

**Comment by kimlimjustin** [comment]
Did you tried on this, and is it works? (since I have no experience with it)

**Comment by kimlimjustin** [comment]
> Don't merge this until the documentation is updated with the latest info of this.

Okay sure

**Comment by im-coder-lg** [comment]
> Did you tried on this, and is it works? (since I have no experience with it)

I have to, I will check it now. Forgot about that 😅

**Comment by im-coder-lg** [comment]
It doesn't seem to work, but don't worry, I will try simple workarounds like running both servers, the workspace won't slow down and you have a choice to choose between app and docs as always. I will make a Gitpod guide file for the contributor that will open immediately after loading up.

**Comment by im-coder-lg** [comment]
Alright, I'd like to call it a day. Last comment for today for me: I added the Gitpod part in the Contributing guide for the website, and am aiming to merge it here so that you don't need to merge two PRs here, I will bundle everything into one package so that you can merge a lot of things immediately.

**Comment by im-coder-lg** [comment]
@kimlimjustin I have added documentation for Gitpod on the Contributing guide page on the Xplorer site and the README, as a shortcut. Now, I tested the docs but I have to test the app's server, which I will do later.

**Comment by im-coder-lg** [comment]
I noticed that there are grammatical mistakes in the docs, so Inwill fix them inside this. Remember the add a description about all the changes so that users can know what has happened.

**Comment by im-coder-lg** [comment]
PS: Can you allow ZVercel for the test deployment? I need to see how the website is right here.

**Comment by kimlimjustin** [comment]
Done

**Comment by im-coder-lg** [comment]
@kimlimjustin it works! The noVNC does work now! Posting a video recording of it later, since I need to set up OBS, etc.

**Comment by im-coder-lg** [comment]
So, we have done these in this PR:

- [ ] Add Gitpod Support with a specific Dockerfile that has a fully-loaded image with noVNC
- [ ] Added simple documentation for Gitpod
- [ ] Corrected grammatical errors
- [ ] Test noVNC and app server

Now, all that is left to do is find a method to replace the greeting window on Gitpod. Then, the PR is ready to be merged.

**Comment by im-coder-lg** [comment]
Marking it as draft, now we have to just make the final lines of code.

**Comment by kimlimjustin** [comment]
Okay, please remember to send me a video record ( since I have no idea what's going on haha )

**Comment by kimlimjustin** [comment]
Sorry I accidentally mark this as ready for preview, changed it back

**Comment by im-coder-lg** [comment]
https://user-images.githubusercontent.com/76845820/135199932-22c78357-9dd2-4903-b709-ddd9403cbe63.mp4

The above file has the Gitpod preview, from how you should start till the app server loaded up on noVNC. That is why I needed a Gitpod Dockerfile. Since I added prebuild code, you can get started immediately, reload and get the servers.

PS: idk why Dendron is loading but the Simple browser shows a preview of the Docusaurus docs.

Extensions used:
* Fluent Product Icon Pack on Open VSX
* VS Code File icons on Open VSX

Extra note: Gitpod uses Open VSX so if you publish your extension on the registry, it will come up on the Registry and therefore, Gitpod.

**Comment by im-coder-lg** [comment]
If you want to test this, click this link: [https://gitpod.io/#https://github.com/im-coder-lg/xplorer/tree/gitpod2.0](https://gitpod.io/#https://github.com/im-coder-lg/xplorer/tree/gitpod2.0)

**Comment by im-coder-lg** [comment]
Remember to reload the site after it successfully loads up.

**Comment by im-coder-lg** [comment]
Alright, this is ready for review. Till now, what changes I made are as follows:

- Add `.gitpod.Dockerfile` and `.gitpod.yml`
- Change `docs/Community/Contributing.md` with the addition of the Gitpod section.
- Modify `README.md` with Gitpod development section
- Modify docs with grammatical error fixes and syntax fixes.

That's it for me.

**Comment by im-coder-lg** [comment]
Last task: Add `ports:` section on Gitpod for rules on when the servers are initiated, what Gitpod should do.

**Comment by kimlimjustin** [comment]
It works like a charm! I'll try around it before merging it! TYSM!

**Comment by im-coder-lg** [comment]
Don't merge it immediately. I need to add a last string of code, for the ports so that when the servers successfully load, they open up on the browser/Simple Browser or they are ignored. I am doing this as we speak, I am looking and analysing the syntax given in the Gitpod Docs.

**Comment by kimlimjustin** [comment]
> Don't merge it immediately. I need to add a last string of code, for the ports so that when the servers successfully load, they open up on the browser/Simple Browser or they are ignored. I am doing this as we speak, I am looking and analysing the syntax given in the Gitpod Docs.

Okay, sure!

**Comment by im-coder-lg** [comment]
Now, it's ready!

**Comment by im-coder-lg** [comment]
Last test now.

**Comment by im-coder-lg** [comment]
Don't merge it yet.

**Comment by im-coder-lg** [comment]
The ports code doesn't work as expected right now but it might so let it stick around here. The PR is officially ready for merge :sunglasses:

**Comment by kimlimjustin** [comment]
Wait, I added the vscode-generator into VSX open registry, and the latest question, how to reload the code? does it support hot reload? Also, the command to start the application with hot reload on Xplorer is `yarn dev` instead of `yarn start`.

Thanks!

**Comment by im-coder-lg** [comment]
Let me change that right now!

**Comment by im-coder-lg** [comment]
Changed and added your extension to the Config :+1:

**Review by kimlimjustin — APPROVED** [review]
It really works like a charm! TYSM!

**Comment by im-coder-lg** [comment]
I have a genuine Xplorer suggestion. Can you try adding some space between buttons? Since I have become used to the Material You and Fluent Design theming where they put some space between buttons, I think if you put some space between the button, it might look neater. Also, try changing the font to Google Sans or something similar that looks flat as well as beautiful.

**Comment by im-coder-lg** [comment]
Excellent! Other than Vercel, everything has succeeded.

**Comment by kimlimjustin** [comment]
WDYM by space between buttons, could you give a screenshot or something, for the font family, it uses the system font as default, but user will be able to customize it by their own (I'm currently working it, you can see branch theme_customization)

**Comment by im-coder-lg** [comment]
I am trying to mean that can you give some space between buttons like 2 
pixels or more so that with the spacing, it looks neater than last time? 
Just imagine, if you stack a cluttered desk and make it neater by adding 
space between everything, you yourself will feel that this was neater than 
before, right? That is what I am asking for Xplorer, some more neatness. If 
you see the Files UX app on Windows, you will think it is very neat, since 
they added a little bit of space between all the buttons. That was what I 
was trying to mean. Try adding some spacing and observe the UI youself, you 
can feel that this is really neat.

**Comment by kimlimjustin** [comment]
Oh, I see,
take a look at the latest commit on the master branch haha
image
Is this good enough? XD

For the vercel issue, I need to take a look into it later before merging.

**Comment by im-coder-lg** [comment]
Ah, that's what I meant! This is looking better than before. I couldn't figure out this since I saw the same thing on noVNC :sweat_smile: but since the noVNC font was smaller, I couldn't figure it out.

**Comment by im-coder-lg** [comment]
> For the vercel issue, I need to take a look into it later before merging.

I also am not sure. Actually, Vercel isn't supposed to fail unless there are issues with the code. Try using the Gitpod link I gave above. To save your time, it is here: https://github.com/kimlimjustin/xplorer/pull/84#issuecomment-929810917

**Comment by im-coder-lg** [comment]
Vercel isn't deploying properly. I opened a new Gitpod Workspace based on the link I posted after the recording, and everything is good, everything is fine there, but not here. I'll be right back.

**Comment by im-coder-lg** [comment]
I think it has to do with the Code of Conduct link inside the support.md file. I will try finding a simple workaround for this, it has to be easy as I think.

**Comment by im-coder-lg** [comment]
Did you check the logs? I think what I told is the problem. Let me change it here, and regarding Gitpod, the ports code does work, all you need to do is allow popups. Since Gitpod creates randomized links every time you create a new session, you have to allow popups continuously.

**Comment by im-coder-lg** [comment]
Ah, now try triggering a preview deployment. I think this issue(Code Of Conduct) is fixed as of now.

**Comment by kimlimjustin** [comment]
Sorry for slow rely (I was having quiz just now), sometimes the docusaurus is indeed buggy, I'll try to fix this

**Comment by im-coder-lg** [comment]
Ah, it's fine. I think I fixed Docusaurus, try a new deployment and can you try allowing me to analyse the build logs? Since I might find the error, I want to see the log.

**Comment by im-coder-lg** [comment]
And instead of triggering a deployment, try authorizing Vercel, so that it will automatically trigger on push.

**Review by kimlimjustin — APPROVED** [review]
Okay, everything passed, thanks!

**Comment by im-coder-lg** [comment]
@kimlimjustin can you do this when you are free? On the README, I added a very important note there. Can you just copy that and add it to the Gitpod section on the Contributing page on the Xplorer site? I forgot about that, so can you just add that line there?
PS: Do it whenever you want but it has to be there, since new contributors on the website has to know that they have to do the reload to get the servers up.

**Comment by im-coder-lg** [comment]
important note=under gitpod section

**Comment by kimlimjustin** [comment]
> @kimlimjustin can you do this when you are free? On the README, I added a very important note there. Can you just copy that and add it to the Gitpod section on the Contributing page on the Xplorer site? I forgot about that, so can you just add that line there? PS: Do it whenever you want but it has to be there since new contributors on the website has to know that they have to do the reload to get the servers up.

Okay, I'll add together with another docs after eating :)

**Comment by im-coder-lg** [comment]
Okay. Everything works nicely now. The Vercel deployment didn't fail, so it was the broken link, which is fixed now. Everything loads exactly as I hoped. I am waiting for a new release and new contributors. Try making a Gitpod Remarks discussion where people can tell any kind of bugs on Gitpod and I will be there to fix it. Since I am (kinda) a Gitpod expert, I could help on it here.

**Comment by kimlimjustin** [comment]
> Okay. Everything works nicely now. The Vercel deployment didn't fail, so it was the broken link, which is fixed now. Everything loads exactly as I hoped. I am waiting for a new release and new contributors. Try making a Gitpod Remarks discussion where people can tell any kind of bugs on Gitpod and I will be there to fix it. Since I am (kinda) a Gitpod expert, I could help on it here.

Thanks, I think the next version (0.2.0) will be released next month since I have to deal with so many items, like the customization (which I'm doing rn) and the issues (you can help if you want to xd)

**Comment by im-coder-lg** [comment]
I'd love to! Maybe I can test it via VNC on Gitpod and give my feedback 
here, that'd be cool xD

**Comment by kimlimjustin** [comment]
> I'd love to! Maybe I can test it via VNC on Gitpod and give my feedback here, that'd be cool xD

Thanks!

**Pull request merged**
