### PR TITLE
Fix typo in homepage

### PR DESCRIPTION
**Pull request by AnilSeervi**
## Motivation
Open Source Contribution
(Write your motivation here.)

## Changes
- Fix typo in Homepage `oraganize`->`organize`
(Write what things you changed)

## Related

(Optional, link(s) of related Issues or PR related to this PR, If this PR adds or changes functionality, please take some time to update the docs and link your PR here.)

## Additional Comments

(Anything, optional)

### CODE REVIEW

**Comment by im-coder-lg** [comment]
Damn, how did I miss that? I recently made a docs fix PR but missed this little typo! Thanks!

**Comment by im-coder-lg** [comment]
Vercel will fail since @kimlimjustin has to give permission for deployment.

**Comment by im-coder-lg** [comment]
Good!

**Comment by AnilSeervi** [comment]
> 
> 
> Damn, how did I miss that? I recently made a docs fix PR but missed this little typo! Thanks!

No Problem.

**Review by kimlimjustin — APPROVED** [review]

**Pull request merged**
