### PR TITLE
optimize doc index page slide show animation and refactor related React code

### PR DESCRIPTION
**Pull request by XDean**
## Motivation

The origin slide animation is not fluent. 
The previous image is disappeared but not fade out.

This PR is to optimize the animation effect and the out-of-date React code.

## Changes

- use React state instead of control DOM element
- use transition instead of keyframe animation

## Related

Origin slide

xplorer-slide-old

New slide

xplorer-slide-new

### CODE REVIEW

**Review by kimlimjustin — APPROVED** [review]

**Comment by XDean** [comment]
Wow @kimlimjustin. You approved so quickly!

**Comment by kimlimjustin** [comment]
> Wow @kimlimjustin. You approved so quickly!

Haha, Thanks tho! Eh, I just realized that you doubled the windows image, it's supposed to be macOS on the third slide, and also you forgot the `alt` of the image. Could you please change it? Thanks

**Comment by XDean** [comment]
Sorry @kimlimjustin . I'm so careless. I will correct it.

**Comment by kimlimjustin** [comment]
> Sorry @kimlimjustin . I'm so careless. I will correct it.

It's okay haha, I don't even realize it when reviewing your code until I see the preview website xd

**Comment by XDean** [comment]
Emm, it's weird. The screenshot gif is correct. Anyway, I have fixed it.

**Comment by kimlimjustin** [comment]
TYSM tho, anyways, any other PRs regarding the website will be appreciated, including [translation](https://github.com/kimlimjustin/xplorer/discussions/30) (cuz I don't have time to edit the website since I got a lot of works with Xplorer itself).

**Pull request merged**
