### PR TITLE
feat: Gitpod support

### PR DESCRIPTION
**Pull request by im-coder-lg**
## Motivation

In issue #69 I had mentioned about Gitpod. For those who don't know about it, Gitpod is a web IDE, kinda similar to GitLab's Web IDE but it offers much customizability. For starters, it offers native VS Code UI on your browser. Gitpod gives a terminal, a Linux one. They offer instant IDEs for new contributors so that they just start off coding. This is really good since people can start immediately without cloning, dependency issues, and a slower computer. Moreover, it's free(no money for Gitpod servers but you _can_ pay for Professional subscriptions if you want) and all you need is a GitHub account to kick-start everything :wink:

## Changes

I have added files mainly, a Gitpod Dockerfile for the custom image, a Gitpod configuration file that contains code for the extensions you put in the `.vscode/extensions.json` as well as terminal tasks for the server. It also contains code for pre-builds for faster Gitpod launching. It appears as though I changed everything but I didn't, it was my PC that did it. I had to clone the fork for the last edits.
Also, a server.sh is added for user choice between app and docs.

## Related

Gitpod: https://gitpod.io

## Additional Comments

This is still in the WIP stage. After I check if the Shell file is working, I will add a button to the README that will start a Gitpod session as well as documentation for this.

### CODE REVIEW

**Comment by im-coder-lg** [comment]
And yeah, docs in another PR as said in the template. Will be done by tomorrow.

**Comment by kimlimjustin** [comment]
I saw there're 386 files changed and most of the theme is just the same (maybe just spacing), is this necessary?

**Comment by im-coder-lg** [comment]
It was due to the cloning, git did that, but it could be helpful to new contributors since this will get them up and running in 5 minutes.

**Comment by im-coder-lg** [comment]
I have to test the shell script since I know that the Gitpod Config won't fail since I had made and configured one of them from scratch. So, there is one test of that, the other is a docs update which will be ready tomorrow in the Contributing section. I will add the button on the docs, README and the CONTRIBUTING.md file for ease.

**Comment by kimlimjustin** [comment]
I'm really sorry but I don't think I can merge this soon as it contains 386 file changes, also 386 file changes will makes the repo size bigger and bigger (because of the git commit history). Or could you just send literally the file that really changes into another PR? (Just copy and paste may be, or use GitHub desktop to manage which file to push)

**Comment by im-coder-lg** [comment]
Hmm... Maybe I can try putting the specific code in another branch and reopen this. I will try this method.

**Pull request closed without merging**
