### PR TITLE
Full refactoring Rust Backend.

### PR DESCRIPTION
**Pull request by Jerrody**
## Motivation
Very **bad** quality of code and style code. Still exist places where code can be improved, but the first step is done.

## Changes
Refactoring Rust Backend with minimal changes.

## Additional Comments

Exist places where code can be improved. Opened a question about what features of `tokio` really needed for the project. Need to close in the future `TODOs`, `FIXMEs` and so on. Many-many work, but I did refactoring because the quality of the code is very bad. I hope that's useful.
Tip! Read Rust Book:
https://doc.rust-lang.org/book/

<a href="https://gitpod.io/#https://github.com/kimlimjustin/xplorer/pull/238"></a>

### CODE REVIEW

**Review by kimlimjustin — COMMENTED** [review]
Overall your modification looks good, but when running it locally, it gives me some following errors:
image

Could you please fix this?

**Comment by Jerrody** [comment]
> Overall your modification looks good, but when running it locally, it gives me some following errors: image
> 
> Could you please fix this?

Update to the latest version of Rust.

**Comment by Jerrody** [comment]
Okay, I fucked up with Linux and MacOS functionality and IDE didn't show me it. Keys time to fix it.

**Comment by kimlimjustin** [comment]
> Okay, I fucked up with Linux and MacOS functionality and IDE didn't show me it. It's time to fix it.

Ohh haha, do you wanna fix it or do you wanna help from me?

**Comment by Jerrody** [comment]
> Ohh haha, do you wanna fix it or do you wanna help from me?

No, thanks. I was busy these days, but now I can fix it.

**Comment by Jerrody** [comment]
@kimlimjustin 
So, what for today. Is everything working for now?

**Review by kimlimjustin — APPROVED** [review]

**Comment by kimlimjustin** [comment]
> @kimlimjustin So, what for today. Is everything working for now?

Please check the errors of CI

**Comment by Jerrody** [comment]
@kimlimjustin 
So, I hope I fixed everything for now :D

**Pull request merged**
