### PR TITLE
fix(gp): Fix command lag with specifc tags

### PR DESCRIPTION
**Pull request by im-coder-lg**
## Motivation

The command actually lags so I discovered a fix. A few days ago, I had a bug with the Gitpod Bot, and one of the people from Gitpod helped me out. During that time, he introduced me to a secret syntax, `before:` which helps you to run that command before the `init:` command. So, I removed the `echo` commands, replaced them with `yarn` and added the `before:` tag to the Docusaurus part.

## Changes

.gitpod.yml file

## Related

(Optional, link(s) of related Issues or PR related to this PR, If this PR adds or changes functionality, please take some time to update the docs and link your PR here.)
Related to #146

## Additional Comments

I have solved one part of it. The Docusaurus error, that seems like a problem so can anybody help on the docs?

### CODE REVIEW

**Comment by im-coder-lg** [comment]
gp -> Gitpod's short form, it's CLI shortcut, etc.

**Comment by kimlimjustin** [comment]
Tbh, I don't understand what issue is it? But anyways, have you tested this? Since I think I'll just merge it (cuz I know nothing about gitpod xd)

**Comment by im-coder-lg** [comment]
> Tbh, I don't understand what issue is it?

The issue is that some commands are getting missed out. So I fixed it.
> But anyways, have you tested this? Since I think I'll just merge it (cuz I know nothing about gitpod xd)

I need to test it, I was busy, but I will test it now.

**Comment by im-coder-lg** [comment]
Not working as expected but I will fix it later.

**Comment by kimlimjustin** [comment]
Okay, thanks!

**Comment by kimlimjustin** [comment]
I think I'll close this one as the rebrand version is being merged. Please send another PR for Gitpod stuff.

Thanks

**Pull request closed without merging**
