### PR TITLE
feat: PWA support

### PR DESCRIPTION
**Pull request by kimlimjustin**
## Changes
Add Progress Web Application support, users can now download and view the docs site locally if their browser supports it (tested on Chrome)

For preview, please check below (vercel bot will comment it)

### CODE REVIEW

**Comment by kimlimjustin** [comment]
Oops, it seems like I accidentally add the commits of changing electron prompt style, so here're what changes:

- restyle the electron prompt theme
- add support for electron prompt to use the parent window theme color scheme
- use xplorer icon for electron prompt

**Comment by stanleyowen** [comment]
Hi @kimlimjustin, in my opinion this blue color looks better - e294d4e1ae281264f8b9610f0ea3ad60bd0116ca

**Comment by kimlimjustin** [comment]
> Hi @kimlimjustin, in my opinion this blue color looks better - [e294d4e](https://github.com/kimlimjustin/xplorer/commit/e294d4e1ae281264f8b9610f0ea3ad60bd0116ca)

Erm okay

**Review by stanleyowen — APPROVED** [review]
Looks Good to Me 👍

**Pull request merged**
