### PR TITLE
Fix Slideshows not displaying images for other languages

### LINKED ISSUE #122: HomePage Slideshow doesn't display images for languages except English
### Description

- The Slideshows images on the [Homepage](https://xplorer.vercel.app/) doesn't display images for homepages of other languages.

### Steps To Reproduce

_No response_

### Expected behavior

- Display images on slideshow

### Xplorer Version

v0.1.0

### Operating System Version

Windows, android

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by AnilSeervi**
## Changes
- Fix Slideshows not displaying images on other languages homepage
- Use `<Link>` tags in other languages homepage
- fix file-preview link in other languages homepage
- Add `sans-serif` fallback font
- Combine google-fonts URL

## Related
- Fixes #122

### CODE REVIEW

**Review by kimlimjustin — APPROVED** [review]
LGTM

**Comment by AnilSeervi** [comment]
I've also removed the `clsx` and used template literals and ternary operator for conditional classes.

**Comment by AnilSeervi** [comment]
> 
> 
> Good Job! Thanks for the contributions! Any other contributions will always be welcomed :)

For now I'm only able to contribute to the docs part of the project because of the apps' requirement and RAM usage.

**Comment by kimlimjustin** [comment]
> I've also removed the `clsx` and used template literals and ternary operator for conditional classes.

It's okay as long as it works haha, website is not my priority tho, but it's always better to have it improve.

> For now I'm only able to contribute to the docs part of the project because of the apps' requirement and RAM usage.

Ah okay. Btw, are you good at designing? If yes, maybe could you please just go and redesign the whole website (make it more elegant), ofc, if you will. Also, the logo of Xplorer seems to need to get redesigned.

Thanks!

**Comment by AnilSeervi** [comment]
> Ah okay. Btw, are you good at designing? If yes, maybe could you please just go and redesign the whole website (make it more elegant), ofc, if you will. Also, the logo of Xplorer seems to need to get redesigned.
> 
> Thanks!

I'm a bit tied cuz of exams now :/
I'm contributing due to hacktoberfest :) otherwise I'd be offline.

**Comment by kimlimjustin** [comment]
> > Ah okay. Btw, are you good at designing? If yes, maybe could you please just go and redesign the whole website (make it more elegant), ofc, if you will. Also, the logo of Xplorer seems to need to get redesigned.
> > Thanks!
> 
> I'm a bit tied cuz of exams now :/ I'm contributing due to hacktoberfest :) otherwise I'd be offline.

Ah okay then.... Gluck for your exams....

**Comment by AnilSeervi** [comment]
I'd be happy to help after.

**Pull request merged**
