### PR TITLE
refactor: use `encodeURI` and `decodeURI` instead of `escape` and `unescape`

### PR DESCRIPTION
**Pull request by kimlimjustin**
## Motivation
`escape` and `unescape` have been deprecated and are not recommended to be used again. 

Ref: https://stackoverflow.com/questions/75980/when-are-you-supposed-to-use-escape-instead-of-encodeuri-encodeuricomponent

## Changes
- replace `escape` and `unescape` with `encodeURI` and `decodeURI`.

## Related

- https://github.com/kimlimjustin/xplorer/pull/225#pullrequestreview-866334386
- https://262.ecma-international.org/9.0/#sec-escape-string

@uahnbu could you please review this?

<a href="https://gitpod.io/#https://github.com/kimlimjustin/xplorer/pull/226"></a>

### CODE REVIEW

**Review by uahnbu — COMMENTED** [review]
Yeah perfecto

**Comment by uahnbu** [comment]
@kimlimjustin Actually I feel quite unnecessary in some parts. It's not required to encode URLs that you're just storing for later. For html displaying, `encodeURI` is used along with `innerHTML` only to prevent HTML injection, and is used to beautify the result.
The later purpose can't be fulfilled using `encodeURI`. Instead `encodeURIComponent` should be the one.
Consider the following substitutions:
```javascript
encodeURI('C:/Windows')
> C:/Windows
encodeURIComponent('C:/Windows')
> C%3A%2FWindows
btoa('C:/Windows')
> QzovV2luZG93cw==
```

**Comment by uahnbu** [comment]
And here's the benchmark for the functions:
image
image

**Comment by kimlimjustin** [comment]
Ye, that makes sense, could you please open a PR regarding this? Thanks in advance

**Comment by uahnbu** [comment]
Yeah I'll. I'm working on the setting sidebar.

**Pull request merged**
