### PR TITLE
Gitpod Rebranding update

### PR DESCRIPTION
**Pull request by im-coder-lg**
## Motivation

Due to #173, Xplorer faced major upgrades. First off, Tauri. Second, JS to TS. Third, Rust. As I use Gitpod mostly for development, and maybe everyone who wants to get a quick IDE, I am making this PR to upgrade  the Gitpod tools so that Xplorer's rebrand can work here.

## Changes

.gitpod.Dockerfile: Not removed anything, added Rust tools, nvm-sh, etc.

## Related

#171 
#173 

## Additional Comments

Draft PR as of now, I am going to commit more changes and test them. @kimlimjustin one thing. Get the Gitpod app, since I added some prebuild code, inside that, I added configs so that if anyone starts a PR, the app will make a comment as a bot.
@stanleyowen can you approve the PR after it's totally ready for merge? Not now, but wait, after I make all the changes, you can approve or request changes.
@kimlimjustin another help, can you tell me how to start the rebranded version using Yarn?

<a href="https://gitpod.io/#https://github.com/kimlimjustin/xplorer/pull/174"></a>

### CODE REVIEW

**Comment by im-coder-lg** [comment]
@kimlimjustn Vercel message

**Comment by im-coder-lg** [comment]
Bet Docusaurus is fine! If there are any changes, do tell me. Apart from .gitpod.yml, I could change other minor things, like grammatical errors, etc.

**Comment by im-coder-lg** [comment]
Looks like it's `yarn dev`, tsting this.

**Comment by kimlimjustin** [comment]
Thanks for your PR!

I've installed this app to this repo, https://github.com/apps/gitpod-io

is this correct? What do I suppose to do after installing?

**Comment by stanleyowen** [comment]
> @stanleyowen can you approve the PR after it's totally ready for merge? Not now, but wait, after I make all the changes, you can approve or request changes.

Sure, of course! Thank you for taking the time for xplorer 😆

**Comment by im-coder-lg** [comment]
> is this correct? What do I suppose to do after installing?

Yes. I'll have to make a test PR _after merging this. You can either merge it(recommended) or I'll close it.

Does Tauri need a keyboard layout package? Seems like that's the reason prebuilds fail. If they still do, I will try adding them to the Gitpod Config.

**Comment by kimlimjustin** [comment]
> You can either merge it(recommended) or I'll close it.

Merge this PR? So is this PR ready for merge? Since you made it as a draft.

> Does Tauri need a keyboard layout package? Seems like that's the reason prebuilds fail. If they still do, I will try adding them to the Gitpod Config.

Tbh, I also don't understand why they need the keyboard layout package but that's what they wrote in the docs.

**Comment by im-coder-lg** [comment]
> Merge this PR? So is this PR ready for merge? Since you made it as a draft.

No. What I meant is that after this PR gets merged, I'll try making another one with some simple changes, like an extra comment or anything else, and you could merge that. If the not message doesn't appear, I'll try asking a person who can help on this.

**Comment by kimlimjustin** [comment]
ah okay, please let me know when this PR is ready cuz I'm not good at GitPod and understand almost nothing (cuz I never used it too xd), btw the new version will be released tomorrow, please help me try it and tell me does it work with Win 7. 

Thanks

**Comment by im-coder-lg** [comment]
Will do. The version appeared on my GitHub feed so I will test it.

**Comment by im-coder-lg** [comment]
We got a hit. I can't get the latest NPM, so gotta stick with Node 12. I will be upgrading to Linux maybe by today/tomorrow. I will try getting the release executable.

**Comment by im-coder-lg** [comment]
Installer ain't launchin'. Best is to get Rust on my PC.

**Comment by kimlimjustin** [comment]
Running the `msi` not working?

**Comment by im-coder-lg** [comment]
Yep. I think Windows 7 won't work from now.

**Comment by im-coder-lg** [comment]
But wait, by tomorrow/the day after tomorrow, I'll get my PC with Zorin OS installed. It's Ubuntu based, so I could test for Linux.
I must be upgrading today it'll take a LOT of time. Gitpod will be failing due to Tauri.

**Comment by kimlimjustin** [comment]
ah okay,  btw do you install webview when running the msi? cuz it needs it

**Comment by im-coder-lg** [comment]
Gitpod works. Well, I didn't install WebView. Do I need it for the installer?

**Comment by kimlimjustin** [comment]
Yes, cuz Xplorer depends it for frontend look

**Comment by im-coder-lg** [comment]
Yu need to allow Vercel. I will test Gitpod.

**Comment by kimlimjustin** [comment]
The vercel bot seems to be buggy, I've approved it but still showing an error, just skip that first, I'll handle that afterward.

**Comment by im-coder-lg** [comment]
Well, another error.
Console log:
```console
$ yarn dev
yarn run v1.22.17
 $ yarn compile && concurrently --kill-others "yarn compile:watch" "yarn sass:watch" "yarn serve" "tauri dev"
 $ webpack && yarn sass && yarn copyfiles
asset index.js 4.94 MiB [compared for emit] (name: main)
runtime modules 309 bytes 2 modules
javascript modules 3.93 MiB
  modules by path ./node_modules/ 3.07 MiB 219 modules
  modules by path ./src/ 884 KiB 80 modules
  3 modules
asset modules 518 KiB 118 modules
json modules 62.7 KiB
  optional modules 40.2 KiB [optional] 16 modules
  modules by path ./lib/*.json 9.15 KiB 2 modules
  ./src/Components/Theme/theme.json 10.7 KiB [built] [code generated]
  ./package.json 2.34 KiB [built] [code generated]
  ./src/Locales/index.json 326 bytes [built] [code generated]
webpack 5.64.1 compiled successfully in 7151 ms
$ sass src/Public/style.scss out/src/Public/style.css
$ node scripts/copyfiles
$ node scripts/sass-watcher.js
$ webpack --watch
$ live-server ./out/src --no-browser
[3]  app:spawn Running "/workspace/xplorer/node_modules/@tauri-apps/cli/bin/tauri-cli tauri dev" +0ms
[3] 
[2] Serving "./out/src" at http://127.0.0.1:8080
[2] Ready for changes
[3]    Compiling app v0.1.0 (/workspace/xplorer/src-tauri)
[3]    Compiling zstd-safe v4.1.1+zstd.1.5.0
[3]    Compiling zstd-sys v1.6.1+zstd.1.5.0
[3]    Compiling bzip2-sys v0.1.11+1.0.8
[3]    Compiling blake3 v1.1.0
[3]    Compiling zbus v1.9.1
[3]    Compiling gobject-sys v0.14.0
[3]    Compiling cairo-sys-rs v0.14.9
[3]    Compiling gobject-sys v0.10.0
[3]    Compiling gdk-pixbuf-sys v0.14.0
[3]    Compiling gio v0.14.8
[3]    Compiling bzip2 v0.4.3
[3]    Compiling soup-sys v0.10.0
[3]    Compiling gdk-sys v0.14.0
[3]    Compiling gio-sys v0.14.0
[3]    Compiling glib v0.14.8
[3]    Compiling pango-sys v0.14.0
[3]    Compiling atk-sys v0.14.0
[3]    Compiling zip v0.5.13
[3]    Compiling gio-sys v0.10.1
[3]    Compiling zstd v0.9.0+zstd.1.5.0
[3]    Compiling gtk-sys v0.14.0
[3]    Compiling tao v0.5.2
[3]    Compiling notify-rust v4.5.4
[3]    Compiling tauri-utils v1.0.0-beta.3
[3]    Compiling gtk v0.14.3
[3]    Compiling webkit2gtk-sys v0.14.0
[3]    Compiling rfd v0.4.4
[3]    Compiling wry v0.12.2
[3]    Compiling tauri-codegen v1.0.0-beta.4
[0] asset index.js 4.94 MiB [compared for emit] (name: main)
[0] runtime modules 309 bytes 2 modules
[0] javascript modules 3.93 MiB
[0]   modules by path ./node_modules/ 3.07 MiB 219 modules
[0]   modules by path ./src/ 884 KiB 80 modules
[0]   3 modules
[0] asset modules 518 KiB 118 modules
[0] json modules 62.7 KiB
[0]   optional modules 40.2 KiB [optional] 16 modules
[0]   modules by path ./lib/*.json 9.15 KiB 2 modules
[0]   ./src/Components/Theme/theme.json 10.7 KiB [built] [code generated]
[0]   ./package.json 2.34 KiB [built] [code generated]
[0]   ./src/Locales/index.json 326 bytes [built] [code generated]
[0] webpack 5.64.1 compiled successfully in 13571 ms
[3]    Compiling cairo-rs v0.14.9
[3]    Compiling pango v0.14.8
[3]    Compiling atk v0.14.0
[3]    Compiling javascriptcore-rs v0.14.0
[3]    Compiling tauri-macros v1.0.0-beta.5
[3]    Compiling gdk-pixbuf v0.14.0
[3]    Compiling gdk v0.14.3
[3]    Compiling webkit2gtk v0.14.0
[3]    Compiling tauri-runtime v0.2.1
[2] GET /vnc.html 404 2.361 ms - 147
[3]    Compiling tauri-runtime-wry v0.2.1
[3]    Compiling tauri v1.0.0-beta.8
[3] warning: unused import: `tauri::api::path::local_data_dir`
[3]    --> src/files_api.rs:517:5
[3]     |
[3] 517 | use tauri::api::path::local_data_dir;
[3]     |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[3]     |
[3]     = note: `#[warn(unused_imports)]` on by default
[3] 
[3] warning: `app` (bin "app") generated 1 warning
[3]     Finished dev [unoptimized + debuginfo] target(s) in 1m 57s
[3]      Running `target/debug/app`
```
And when I open the noVNC page, it looks like the first time I made my website, like HTML. Might be noVNC's problem, but maybe if you try fixing the error, this might work.
PS: Indented this log with a space to prove it's the console, not me:
> ```console
>  $ yarn compile && concurrently --kill-others "yarn compile:watch" "yarn sass:watch" "yarn serve" "tauri dev"
>  $ webpack && yarn sass && yarn copyfiles
> ```

**Comment by kimlimjustin** [comment]
It's not an error tho, just a warning....

**Comment by kimlimjustin** [comment]
Does it work rn?

**Comment by im-coder-lg** [comment]
Whoops totally forgot about this one. I had a kinda bad health recently(having it now) so didn't check much on GitHub, except notifications. Testing it soon.

**Comment by kimlimjustin** [comment]
Closing this as #197 getting merged

**Pull request closed without merging**
