### PR TITLE
Properties style

### PR DESCRIPTION
**Pull request by dkhd**
## Motivation

This issue here #72 and mention here #131 

## Changes

Enhance the UI for file/directory properties.

1. Fixed width (but flexible height) with auto-break filename
2. Capitalize the first letter of `isHiddenFile` 
3. Adding colon
4. Increasing some padding & margin
5. Format the date & time for `Created At`, `Modified At`, and `Accessed At`

See screenshots below

properties

properties

I also added [MomentJS](https://momentjs.com/) module to format the time, `yarn.lock` modified by system.

## Related

This issue here #72 and mention here #131 

## Additional Comments

_none_

### CODE REVIEW

**Comment by Turbinya** [comment]
I think it's better to use Luxon instead of Moment https://moment.github.io/luxon/#/formatting?id=presets. Moment is very big, obsoleted and depricated.
Or try using: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat/DateTimeFormat so as not to increase the size of the application at all

**Comment by dkhd** [comment]
Nice suggestion @Turbinya, I'll take a look at it.

**Comment by kimlimjustin** [comment]
Both #131 and #133 proposed good styling, I think I'll combine these both PRs (by taking #131's center styling and other from this), also @dkhd do you realize that #132 code is also here?

**Comment by dkhd** [comment]
Ah, my bad. Sorry I didn't check that. You can combine both of them of
course.

**Pull request merged**
