### PR TITLE
Fix typo in README.md

### PR DESCRIPTION
**Pull request by AlexHladin**
## Motivation
Fix typo.

## Changes
Fixed typo.

## Related

(Optional, link(s) of related Issues or PR related to this PR, If this PR adds or changes functionality, please take some time to update the docs and link your PR here.)

## Additional Comments

(Anything, optional)

<a href="https://gitpod.io/#https://github.com/kimlimjustin/xplorer/pull/206"></a>

### CODE REVIEW

**Review by kimlimjustin — APPROVED** [review]

**Review by stanleyowen — APPROVED** [review]

**Review by im-coder-lg — COMMENTED** [review]
Also, can you add a `a` between `Rrcommend us` and `feature`? Grammar error, it's best corrected here.

**Comment by AlexHladin** [comment]
@im-coder-lg done.

**Comment by im-coder-lg** [comment]
Thanks! LGTM

**Review by kimlimjustin — CHANGES_REQUESTED** [review]
Oh yeah, could you please edit the [docs site page](https://xplorer.space/docs/intro/) too together with this?

**Comment by im-coder-lg** [comment]
> Oh yeah, could you please edit the [docs site page](https://xplorer.space/docs/intro/) too together with this?

Who, me or @AlexHladin? Confused.

**Comment by kimlimjustin** [comment]
@AlexHladin ofc, he opened this PR haha, but if he doesn't respond in 48 hours, then please edit it @im-coder-lg .

**Comment by im-coder-lg** [comment]
I know that @AlexHladin will, but I also need to check some things in the documentation. Will open a PR soon, maybe by the second week of January after finding the typos.

**Comment by AlexHladin** [comment]
> @AlexHladin ofc, he opened this PR haha, but if he doesn't respond in 48 hours, then please edit it @im-coder-lg .

@kimlimjustin sorry, not really understand what should I edit. Could you clarify it?
Btw, I just saw an issue in the Readme.md and I've decided to fix it immediately, not sure that this action requires something else.

**Comment by kimlimjustin** [comment]
Oh, this is [the source to the site docs](https://github.com/kimlimjustin/xplorer/blob/master/docs/docs/intro.md), could you please update that together with this PR? cuz there's the same typo there too (I copied it when writing it hehe), thanks a lot

**Comment by AlexHladin** [comment]
> Oh, this is [the source to the site docs](https://github.com/kimlimjustin/xplorer/blob/master/docs/docs/intro.md), could you please update that together with this PR? cuz there's the same typo there too (I copied it when writing it hehe), thanks a lot

@kimlimjustin ok, will do it

**Comment by AlexHladin** [comment]
@kimlimjustin done

**Pull request merged**
