### PR TITLE
Rebranding of Xplorer

### LINKED ISSUE #157: Current Implementation of Theme Plugin can Cause Critical Security Concern
### Description

The theme customization allows user to configure the theme dynamically, however it also allow hackers to inject malicious code which may cause critical security issue.

### Steps To Reproduce

1. Edit the theme file (*.js)
2. Insert script such as `document.body.innerHTML = '';`
3. Run the script

### Expected behavior

Users are able to customize the theme (via another approaches) without having any security concerns.

### Xplorer Version

v0.1.0

### Operating System Version

Windows 11 Version 21H2 (Build 22000.258)

### Additional Information

It will be better if users could customize the theme via GUI like how windows 11 implement it.

### PR DESCRIPTION
**Pull request by kimlimjustin**
## Motivation
#171 

## Changes
- Remove all dependencies related to Electron
- Add Tauri dependencies
- Reimplement all code to use Rust as the backend for file operation
- Allow previewing almost all programming languages with syntax highlighting
- Improve file type determination performance (x3 faster) (33ee1ac)
- Improve open directory performance
- Improve memory usage (won't consume as much as the previous release)
- Decrease the size of the installer
  - Windows Installer from 67.2 MB to 5.75 MB (decrease up to 91.44 percent)
  - Deb Installer from 68.8 MB to 7.57 MB (decrease up to 90 percent)
  - Dmg Installer from 87.6 MB to 5 MB (decrease up to 94.29 percent)
- Fix sidebar favorites not sync with home page favorites bug
- Add ability to continue the previous session on startup
- Add ability to change Fonts, Window Transparency, Frame style, and many more
- Improve Xplorer layout
- Introduce a new icon
- Improve locales
- Update docs
- Improve lazy load thumbnail algorithm
- Add more tests
- Improve calculate folder's size speed (even faster than windows' default file explorer)
- Remove monorepo setup and temporarily remove theme customization support as it gives security concerns (resolve #157) (will be added back in the future)
- Add default sorting algorithm for specific folders
- Improve update theme performance
- Update icons and file type library
- Add go to parent directory navigation.

and so on...

## Performance
Tested on i7-9700 32GB
| | Before | After |
| ---- | ---- | ---- |
| First startup | ∼ 1.52 s | ∼ 1.28 s |
| Speed on opening [material icon folder](https://github.com/PKief/vscode-material-icon-theme/tree/main/icons) | ∼0.5 s | ~1.5s |
| Memory used on opening [material icon folder](https://github.com/PKief/vscode-material-icon-theme/tree/main/icons) | 284 MB | 220 MB |
| RAM usage stability | Not Stable | More Stable |

## Related
- Resolve #157 
- Might fix (need confirmation):
  - #153 
  - #152 
  - #77 
  - #66 

## Some issues introduced:
(will be fixed in the future release)
- [ ] High amount of memory needed to listen to drive changes
- [ ] Current approach to extract exe icon is by calling `ps1` files underneath the hood
- [ ] `xplorer://Trash` is not supported on macOS

### CODE REVIEW

**Review by stanleyowen — CHANGES_REQUESTED** [review]
Great work! Love it really much. However I notice that the maximize button doesn't work appropriately, can you confirm it?

**Comment by im-coder-lg** [comment]
Been a long time... Does the rebrand still have C++ modules?

**Comment by kimlimjustin** [comment]
> Been a long time... Does the rebrand still have C++ modules?

Just wanna tag you for the gitpod things haha. The rebrand does not longer contain c++ modules, instead, there're Rust files. Could you please help me handle this?

This is the setup for Linux: https://tauri.studio/en/docs/getting-started/setup-linux

Thanks

**Comment by im-coder-lg** [comment]
Will do soon 👍🏻

**Review by stanleyowen — APPROVED** [review]
LGTM

**Comment by ivanglushko** [comment]
Curios how Tauri is in production thanks for a great example guys 🔥

**Pull request merged**
